"""added venue_name to Venue model.py

Revision ID: 1eb10edd611d
Revises: 66be3884a536
Create Date: 2024-03-05 13:42:07.553679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb10edd611d'
down_revision = '66be3884a536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_name', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_venues_venue_name'), ['venue_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_venues_venue_name'), type_='unique')
        batch_op.drop_column('venue_name')

    # ### end Alembic commands ###
